### PR TITLE
[Opus and Vorbis] Add required gst-caps for those codecs to work

### PR DESCRIPTION
**Pull request by lukiwa**
For Opus - providing gstreamer with streamheader capability to properly detect number of channels.
For Vorbis - provided channels and rate capabilities.

### CODE REVIEW

**Comment by modeveci** [comment]
@neeraj-deshpande Can you try this PR on your working setup? This is needed to correct the maximum supported channel number and let the sinks get audio configurations from caps. If it is ok for you, then we can merge with master. Thanks

**Comment by neeraj-deshpande** [comment]
Sure. I will try it.

**Review by neeraj-deshpande — COMMENTED** [review]
Tested the pull request with RPI3/buildroot main.
Observed that Opus tests (3, 31, 32) on YTLR 2021 EME conformance page are not working with it.

**Review by neeraj-deshpande — COMMENTED** [review]
The pull request seems to be working on RPI.
But I am not seeing SbAudioSinkGetMaxChannels being called any time.
Some implementation exists in platform specific directory e.g. SbMediaGetAudioConfiguration. That is being called.

**Review by modeveci — APPROVED** [review]

**Pull request merged**
