### PR TITLE
Modified Cobalt browser to play secondary video on PIP window.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by neeraj-deshpande** [comment]
This pull request needs to be tested on Broadcom platform.

**Comment by pawel-stanek-ml** [comment]
This code is platform independent. Let's leave it like this

**Comment by neeraj-deshpande** [comment]
Hi Pawel :-)
There is a dual video test in YTLR. 
On Broadcom, second video works only in PIP window. Where this change can be done?

**Comment by pawel-stanek-ml** [comment]
It has to be abstracted out and done in brcm directory.

**Review by MFransen69 — APPROVED** [review]

**Pull request merged**
