### PR TITLE
Fix for issue where periodic Widevine license request fails alternatively.

### PR DESCRIPTION
**Pull request by ghost**
When Widevine protected YouTube content is played for longer time, Widevine generates License Request at regular interval.
Here every alternate License Request fails with following log:
[1347:0323/145359.379780:INFO:drm_system_ocdm.cc(277)] Process challenge for ksidF84ABAAE type 1
[1258:0323/145359.380545:ERROR:drm_system.cc(225)] Unknown session update request ticket: 2.

### CODE REVIEW

**Comment by neeraj-deshpande** [comment]
> Why?
Hi Pawel :-)
This happens when same YT content is played for some time and Widevine generates multiple periodic license requests. I will try to explain:
--Here when DrmSystemOcdm::UpdateSession (for license response) is called, a ticket is generated. This ticket has to be used with corresponding session_updated_callback_ which is called in  OnAllKeysUpdated callback.
--Here OnAllKeysUpdated is called only for first opencdm_session_update(). When next license response arrives,  OnAllKeysUpdated is not called and the ticket remains unused.
--The same unused ticket is used with the subsequent license request where Cobalt discards the request with following error log:
1258:0323/145359.380545:ERROR:drm_system.cc(225)] Unknown session update request ticket: 2.
--But as the ticket is used now, the next periodic license request succeeds. It keeps on happening alternatively.

**Comment by pawel-stanek-ml** [comment]
I understand  that but I meant why it's not always called? It looks to me the bug is somewhere else because every update should result in OnAllKeysUpdated() (even if no key got updated - it's a part of the contract indicating the update is done)

**Comment by pawel-stanek-ml** [comment]
And yeah. Hi Neeraj! Big brother is watching ;)

**Comment by neeraj-deshpande** [comment]
OnAllKeysUpdated() is called when Widevine calls onKeyStatusesChange() IEventListener callback.
Widevine calls onKeyStatusesChange() if there is change in the keys.
It doesn't call onKeyStatusesChange() for every license response.

**Comment by pawel-stanek-ml** [comment]
Yes and that's the missing bit. The fix IMO should be to detect that and call IMediaKeySessionCallback::OnKeyStatusesUpdated() in WV (so for all products and not cobalt only)

**Comment by pwielders** [comment]
@neeraj-deshpande I guess this is the pull request I added to the Widevine where the KeySattusUpdate is now called. Correct? So this can be closed ?

**Pull request closed without merging**
